### ISSUE TITLE
ssd

### ISSUE THREAD

**Issue by kaishijeng** [OAID/mxnetOnACL#4]
I follow the instruction of example/ssd and  run python  demo.py from example/ssd directory and got an error below. My platform is firefly 3399. Is there a reason which ssd example is not working?

[21:15:32] /home/firefly/2TB/src/firefly/mxnetOnACL/dmlc-core/include/dmlc/./logging.h:304: [21:15:32] src/core/symbolic.cc:72: Symbol.ComposeKeyword argument name anchors not found.
Candidate arguments:
        [0]cls_prob
        [1]loc_pred
        [2]anchor

Stack trace returned 7 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet-0.10.1-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x44) [0x7f7a5b1cb4]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet-0.10.1-py2.7.egg/mxnet/libmxnet.so(_ZN4nnvm23KeywordArgumentMismatchEPKcRKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS8_EERKN4dmlc10array_viewIS8_EE+0x434) [0x7f7b095604]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet-0.10.1-py2.7.egg/mxnet/libmxnet.so(_ZN4nnvm6Symbol7ComposeERKN4dmlc10array_viewIPKS0_EERKSt13unordered_mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES4_St4hashISE_ESt8equal_toISE_ESaISt4pairIKSE_S4_EEERSK_+0xcc4) [0x7f7b0922cc]
[bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet-0.10.1-py2.7.egg/mxnet/libmxnet.so(NNSymbolCompose+0x238) [0x7f7b0a1188]
[bt] (4) /usr/lib/aarch64-linux-gnu/libffi.so.6(ffi_call_SYSV+0x64) [0x7f7bfd1e60]
[bt] (5) /usr/lib/aarch64-linux-gnu/libffi.so.6(ffi_call+0xc0) [0x7f7bfd27b8]
[bt] (6) /usr/lib/python2.7/lib-dynload/_ctypes.aarch64-linux-gnu.so(_ctypes_callproc+0x670) [0x7f7bff1b30]

Traceback (most recent call last):
  File "demo.py", line 99, in <module>
    ctx, args.nms_thresh, args.force_nms)
  File "demo.py", line 40, in get_detector
    .get_symbol(len(CLASSES), nms_thresh, force_nms)
  File "/home/firefly/2TB/src/mxnetOnACL/example/ssd/symbol/symbol_vgg16_ssd_300.py", line 179, in get_symbol
    net = get_symbol_train(num_classes)
  File "/home/firefly/2TB/src/mxnetOnACL/example/ssd/symbol/symbol_vgg16_ssd_300.py", line 150, in get_symbol_train
    variances=(0.1, 0.1, 0.2, 0.2), nms_topk=nms_topk)
  File "<string>", line 47, in _contrib_MultiBoxDetection
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.10.1-py2.7.egg/mxnet/_ctypes/symbol.py", line 136, in _symbol_creator
    s._compose(name=name, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.10.1-py2.7.egg/mxnet/symbol.py", line 419, in _compose
    self.handle, name, num_args, keys, args))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.10.1-py2.7.egg/mxnet/base.py", line 85, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [21:15:32] src/core/symbolic.cc:72: Symbol.ComposeKeyword argument name anchors not found.
Candidate arguments:
        [0]cls_prob
        [1]loc_pred
        [2]anchor

Stack trace returned 7 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet-0.10.1-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x44) [0x7f7a5b1cb4]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet-0.10.1-py2.7.egg/mxnet/libmxnet.so(_ZN4nnvm23KeywordArgumentMismatchEPKcRKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS8_EERKN4dmlc10array_viewIS8_EE+0x434) [0x7f7b095604]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet-0.10.1-py2.7.egg/mxnet/libmxnet.so(_ZN4nnvm6Symbol7ComposeERKN4dmlc10array_viewIPKS0_EERKSt13unordered_mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES4_St4hashISE_ESt8equal_toISE_ESaISt4pairIKSE_S4_EEERSK_+0xcc4) [0x7f7b0922cc]
[bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet-0.10.1-py2.7.egg/mxnet/libmxnet.so(NNSymbolCompose+0x238) [0x7f7b0a1188]
[bt] (4) /usr/lib/aarch64-linux-gnu/libffi.so.6(ffi_call_SYSV+0x64) [0x7f7bfd1e60]
[bt] (5) /usr/lib/aarch64-linux-gnu/libffi.so.6(ffi_call+0xc0) [0x7f7bfd27b8]
[bt] (6) /usr/lib/python2.7/lib-dynload/_ctypes.aarch64-linux-gnu.so(_ctypes_callproc+0x670) [0x7f7bff1b30]

Thanks,

**Comment by kaishijeng** [comment]
I have tested  SSD from Incubator-mxnet head and it runs OK.
Do you have a plan to update mxnet to incubator-mxnet?
With this update, SSD maybe work OK.

Thanks
